### PR TITLE
Update doctrine annotation usage to avoid memory leaks

### PR DESCRIPTION
**Pull request by mikeSimonson**
https://github.com/doctrine/annotations/pull/162

### CODE REVIEW

**Comment by mikeSimonson** [comment]
I just don't know why travis fails. I can't reproduce the failure locally and it seems like it failed a while ago.

**Comment by enumag** [comment]
Travis fails because of BC break in PHPUnit. I will work when next version of Codeception is out.

**Comment by enumag** [comment]
Also I don't think this change is necessary. The `registerLoader` method is only called for tests of this package.

This could be relevant for Kdyby/Annotations though. Could you send a PR there?

**Comment by mikeSimonson** [comment]
@enumag will do

**Comment by enumag** [comment]
Thanks!

**Pull request closed without merging**
