### PR TITLE
Fix too few arguments

### PR DESCRIPTION
**Pull request by josefsabl**
This trivial change solves the problem. I am not sure if I broke something else. I guess not. Sorry for not running tests etc ... :-)
https://github.com/Arachne/EntityLoader/issues/4

### CODE REVIEW

**Comment by enumag** [comment]
Well I'm not entirely sure what to do here. This change will break Verifier when used with Kdyby/Events instead of Contributte.

**Comment by enumag** [comment]
Hmm maybe not. Need to check a few things...

**Comment by enumag** [comment]
Oh I see now. Change the required nette/application version to 2.4.11 and it should be ok.

**Comment by enumag** [comment]
Don't worry about failing tests. It's caused by outdated dependencies. I'm working on that but it depends on other packages so it might take a while.

**Comment by josefsabl** [comment]
> Oh I see now. Change the required nette/application version to 2.4.11 and it should be ok.

Ok, I fixed the nette/application to version 2.4.11, I had to loosen the arachne/entity-loader dependency as v0.13.0 conflicts with 2.4.11. I am on entity-loader 0.12.2 now but now I get `Class 'Contributte\Events\Extra\DI\EventApplicationBridgeExtension' not found`.

Well, I don't feel like messing with my app too much at the moment. Do you feel this issue will be fixes anytime soon? Because I am quite happy with my temporary fix for the time being :-)

UPDATE: Looks like [this](https://github.com/contributte/event-dispatcher-extra/issues/15#issuecomment-403472567) comment is the most fresh in this "double thread" so I will follow this. Keep my patched version and wait for updated official one. Am I correct? :-)

**Comment by enumag** [comment]
> I had to loosen the arachne/entity-loader dependency as v0.13.0 conflicts with 2.4.11.

Wait what? Can you be more specific? I'm not aware of any issues with EntityLoader 0.13 and Nette 2.4.11. The problem in Contributte has been resolved I hope?

**Comment by enumag** [comment]
ping @josefsabl

**Comment by enumag** [comment]
Closed by https://github.com/Arachne/Verifier/commit/034178655632831873b31563bb3ef974b5c750fc.

**Pull request closed without merging**
